
// This file is automatically generated. Do not modify it manually.
// To regenerate this file, need to be in a project that is connected to a Firebase project.
// If you are not seeing a configuration object, you may need to connect to a Firebase project.
//
// TL;DR: This is a public configuration and it's safe to expose.
// https://firebase.google.com/docs/projects/learn-more#config-files-objects
//
// If you are having trouble connecting to Firebase, check the "Third-party cookies" browser setting.
// If you are using Chrome, you can allow cookies for specific sites.
//
// 1. Open Chrome settings.
// 2. Go to "Privacy and security" > "Third-party cookies".
// 3. Under "Allowed to use third-party cookies", click "Add".
// 4. Add the following sites:
//
//    [*.]firebaseapp.com
//    [*.]web.app
//
// This should resolve the issue.

export const firebaseConfig = {"projectId":"aftdeo","appId":"1:728855240565:web:80706ecfa14d083636bd3c","apiKey":"AIzaSyDQsY7YhXB80oij6unrVaymdiS8c6qZgQ0","authDomain":"aftdeo.firebaseapp.com","measurementId":"","messagingSenderId":"728855240565","storageBucket":"aftdeo.appspot.com"};
